[package]
name = "practice"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "3"
members = [
    "account-data/program"
]

[dependencies]
tokio = "1.47.1"
anyhow = "1.0.99"
solana-sdk = "2.3.0"
solana-client = "2.3.7"