[package]
name = "cross-program-invocatio-native-lever"
version = "0.1.0"
edition = "2024"

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]

[dependencies]
solana-program = "2.3.0"
borsh = "1.5.7"

[lib]
crate-type = ["cdylib", "lib"]